# Generated by Django 4.2 on 2023-04-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temporada', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Temporada',
        ),
        migrations.AlterModelOptions(
            name='temporada',
            options={'verbose_name': 'temporada', 'verbose_name_plural': 'temporadas'},
        ),
    ]
